export const bg = '#36802d';
export const lightWhite= '#fcefe9';
export const inputPlaceholder = '#c9df8a';
export const lighterWhite= '#f4e4e2';
export const circleInactive = '#c9df8a';
export const circleActive = '#c9df8a';
export const itemListText= '#555';
export const itemListTextStrike= '#c4c4cc';
export const deleteIconColor= '#bc2e4c';
